name: ARM64 Build and Deploy

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build and Push?"
        required: true
        default: true
        type: boolean
      deploy:
        description: "Deploy?"
        required: true
        default: false
        type: boolean

jobs:
  build_server:
    name: Build server (ARM64)
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ARM64 builder
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/arm64  # 锁定构建器为ARM64

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/arm64  # 强制指定目标架构
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/texas-poker-game:api-arm64-latest

  build_client:
    name: Build client (ARM64)
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ARM64 builder
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/arm64

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/texas-poker-game:nginx-arm64-latest
