name: Build and Publish Docker image

on:
  release:
    types: [published]
  push:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get git commit date
        id: date
        run: |
          echo "commit_date=$(git show -s --format=%cd --date=format:%Y%m%d-%H%M%S ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ env.commit_date }}
          RELEASE_NAME: nightly-release-${{ env.commit_date }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Server - Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          build-args: |
            NODE_ENV=production
            IDENTIFY_VERSION_KEY=${GITHUB_SHA}
          push: true
          tags: |
            lionyuyu/texas-poker-game:api-latest
            lionyuyu/texas-poker-game:api-${{ github.event.release.tag_name || env.commit_date }}

      - name: Client - Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          build-args: |
            NODE_ENV=production
            VUE_APP_API_IP=${VUE_APP_API_IP}
            VUE_APP_API_PORT=${VUE_APP_API_PORT}
            IDENTIFY_VERSION_KEY=${GITHUB_SHA}
          push: true
          tags: |
            lionyuyu/texas-poker-game:nginx-latest
            lionyuyu/texas-poker-game:nginx-${{ github.event.release.tag_name || env.commit_date }}
