name: Build, Publish Docker image, and deploy

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Build and Push?"
        required: true
        default: true
        type: boolean
      deploy:
        description: "Deploy?"
        required: true
        default: false
        type: boolean

jobs:
  build_server:
    name: Build server docker and push.
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get git commit date
        id: date
        run: |
          echo "commit_date=$(git show -s --format=%cd --date=format:%Y%m%d-%H%M%S ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/arm64  # 新增架构支持配置

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Server - Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/arm64  # 新增目标架构
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            IDENTIFY_VERSION_KEY=${{ github.sha }}
          push: true
          tags: |
            fisher101/texas-poker-game:api-latest

  build_client:
    name: Build client docker and push.
    runs-on: ubuntu-latest
    if: ${{ inputs.build }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get git commit date
        id: date
        run: |
          echo "commit_date=$(git show -s --format=%cd --date=format:%Y%m%d-%H%M%S ${GITHUB_SHA})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/arm64  # 新增架构支持配置

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Client - Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/arm64  # 新增目标架构
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            IDENTIFY_VERSION_KEY=${{ github.sha }}
          push: true
          tags: |
            fisher101/texas-poker-game:nginx-latest

