name: Build Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test build for server
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: ./server/yarn.lock
      - run: |
          yarn install --frozen-lockfile
          yarn build
        working-directory: ./server

  build_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test build for client
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: ./client/yarn.lock
      - run: |
          yarn install --frozen-lockfile
          yarn build
        working-directory: ./client
