# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test build for server
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2
        cache: 'yarn'
    - working-directory: ./server
      run: |
        yarn install --frozen-lockfile
        yarn build
        
    - name: Test build for Client
      uses: actions/setup-node@v4
      with:
        node-version: 10.24.1
        cache: 'yarn'
    - working-directory: ./client
      run: |
        yarn install --frozen-lockfile
        yarn build
